### ISSUE TITLE
How to display all array objects?

### ISSUE THREAD

**Issue by skorotkiewicz** [Usbac/tundra#4]
Like this?

```javascript
{% foreach (myarr as arr) { %}
    <p>{{arr.name}}</p>
{% } %}
```

**Comment by Usbac** [comment]
Hello @skorotkiewicz! You can print an array with the following syntax:

```html
{% for (let key in list) { %}
    <p>key is: {{ key }}</p>
    <p>value is: {{ list[key] }}</p>
{% } %}
```
Any Js code can be put between the `code` tags, so you are free to choose how to do iterations.

Also you can use the `:` and `end` tags instead of the curly brackets, this is just syntactic sugar and works the same. :)

```html
{% for (let key in list): %}
    <p>key is: {{ key }}</p>
    <p>value is: {{ list[key] }}</p>
{% end %}
```
Regards!

**Comment by skorotkiewicz** [comment]
Thank you for your quick answer, your project is really great, I thought it was a copy of Swig but Tundra is much better!
I also like it that I can easily add my own functions in stdlib.js. ^_^

Thank you for a great project. :)

Greetings from Germany!
